export default {
    perPage: ["10", "25", "50", "100"],
    pagination: {
        lastPage: "",
        currentPage: "",
        total: "",
        lastPageUrl: "",
        nextPageUrl: "",
        prevPageUrl: "",
        from: "",
        to: ""
    },
    pagination2: {
        lastPage: "",
        currentPage: "",
        total: "",
        lastPageUrl: "",
        nextPageUrl: "",
        prevPageUrl: "",
        from: "",
        to: ""
    },
    TotalItemNotAvailable: 0,
    errors: {},
    priceCount: "",
    PriceChangeInfo: [],
    ItemsNotAvailable: [],
    Stores: [],
    Barangays: [],
    Towns: [],
    Provinces: [],
    Transportations: [],
    Departments: [],
    Tenants: [],
    filterTowns: [],
    filterBarangays: [],
    RangeLevel: [],
    UserTypes: [],

    MinOrders: [],
    Employees: [],
    Items: [],
    ItemCategory: [],
    PriceGroup: [],
    Instructions: [],
    Liquidation: [],
    Transactions: [],
    Accountability: [],

    OrderDataReport: [],
    MostCancelledItems: [],
    HourlyCallMonitoring: [],
    Commission: [],
    SelectedTenant: [],
    FoodUsertype: [],

    Roles: [],
    GlobalCategory: [],
    BuGroup: [],
    Disc: []
};
